name: game_loop
version: 0.6.0
author: John McCutchan <john@johnmccutchan.com>
description: The Game Loop for Dart
homepage: https://github.com/johnmccutchan/game_loop
dependencies:
  unittest: any
  browser: any
